email_max_length: 50
name_max_length: 50
pass_min_length: 6
per_page: 10
time_zone: "Hanoi"
doc_min_length: 3
doc_max_length: 255
category_min_length: 3
category_max_length: 50
doc_size: 50
doc_type: [application/pdf, application/msword, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.presentationml.presentation]
doc_type_html: "application/pdf, application/msword, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.presentationml.presentation"
pdf_type: application/pdf
